### ISSUE TITLE
Power of 2 shapes don't compile

### ISSUE THREAD

**Issue by soundeffects** [bonsairobo/ndshape-rs#3]
I get a compiler error whenever I try to use a ConstPow2Shape3u32 or ConstPow2Shape3usize. When I replace the power of 2 shapes with their normal versions, my code compiles fine. Here's the error I get from the compiler:

```
error[E0080]: evaluation of `<ndshape::ConstPow2Shape3u32<32_u32, 32_u32, 32_u32> as ndshape::ConstShape<3_usize>>::SIZE` failed
   --> /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/ndshape-0.3.0/src/const_shape.rs:249:1
    |
249 | impl_const_pow2_shape3!(ConstPow2Shape3u32, u32);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to shift left by `96_u32`, which would overflow
    |
    = note: this error originates in the macro `impl_const_pow2_shape3` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Do power of 2 shapes have additional limitations I'm not aware of? Is this a bug in the macro?

**Comment by bonsairobo** [comment]
I'm pretty sure you are trying to use the type `ConstPow2Shape3u32<32, 32, 32>`, which won't work because the const generics in a pow2 shape mean something different from other shapes. You should instead use `ConstPow2Shape3u32<5, 5, 5>`, because 2^5 = 32.

**Comment by soundeffects** [comment]
That's what I missed, it works now. Thanks!
